language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g grunt-cli
services:
  - redis-server
env:
  - "PORT=9090 ALLOWED_CORS_DOMAINS=\"http://localhost:7777\" NODE_ENV=\"development\" ENABLE_GELF_LOGS=false SESSION_SECRET=\"secret value\" FORCE_SSL=false LOGIN_SERVER_URL_WITH_AUTH=\"http://localhost:3000\" AUTHENTICATION_PROVIDER=\"passport-webmaker\" ENABLE_PATH_ROUTE=true ENABLE_JSON_ROUTE=true ENABLE_ZIP_ROUTE=true MAX_SYNC_SIZE_BYTES=2000000"
